name = "PAMSO"
uuid = "1b84e714-819e-4501-85a9-ebfadece37ed"
authors = ["Asha Ramanujam"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
