name = "PAMSO"
uuid = "2425fc65-9120-48c9-bb20-0cbf0cdb80e9"
authors = ["Asha Ramanujam"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
